### ISSUE TITLE
App currently not working as expected because of error in API

### ISSUE THREAD

**Issue by nosurveillance** [austrianredcross/stopp-corona-android#16]
At the time of writing this issue the endpoint to request an SMS TAN throws a 404 error and has been doing so for several hours.

As the SMS TAN is required to confirm an infection and trigger yellow/red warnings, this means that nobody will be warned of an infection as the SMS TAN can't be triggered and will therefore never be received and can therefore not be used as a confirmation token.

**Comment by nosurveillance** [comment]
Deactivating this endpoint over night was probably a panic reaction to the (now deleted) issue regarding the possibility of using the RequestTan API for spamming.

However, silently doing this and leaving users with unexplained error messages does not build trust.

**Comment by mitsuhiko** [comment]
I removed a reference to the issue you opened earlier. Your issue was not deleted, it was moved to an internal repository until further verification. I would ask you again to please use [responsible disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure) through a private email address to discuss security related issues.

I informed the developers about the backend error. I'm closing the issue here because it is an issue with the backend service and not the app. There will be a separate repository for the backend and meta discussions opened later. This is all work in progress and I hope for your understanding.
