### ISSUE TITLE
Remove Play Store geolock

### ISSUE THREAD

**Issue by evilscientress** [austrianredcross/stopp-corona-android#19]
Geo locking the app via the Play Store is a bad idea. It **doesn't** lock it to users within Austria, it locks it to users who set their Play Store to that region, and that only be changed once every couple months. So it prevents a lot of users from using it, who are in Austria but have set their Play Store account to a different region, for example because they are a seasonal worker or "Grenzgänger", or any other number of reasons.

Gelocking the App prevents all of those people to use the app. It also doesn't prevent malicious usage. Anyone can still get the APK from the Play Store, which can be downloaded with various tools, and install it manually.

The same applies to Apple's App Store.

**Comment by aufziehvogel** [comment]
Affected person here: I currently live in Austria, but never switched my App store to Austria - it's still set to Germany. To my knowledge I need to fulfill two requirements to be able to change settings of the Play Store to Austria, both of which I currently cannot fulfill:

1. To be able to switch region settings, I have to provide Google with a payment method (e.g. a credit card), which I do not want to do (I totally do not understand why Google demands this, but the button to change region settings is grayed out and according to my research this is because I did not provide a payment method)
2. After I switched regions I cannot switch it back for one year, which does not work for me as I am planning to move to another country in this time span

My suggestion - from how I understood the feedback I got from the red cross - would be to display a notification somewhere in the App that states that the app is only useful in Austria. My understanding was that the red cross was afraid that people install the app in other countries and then do now know what to do with it or why it does not work.

**Comment by Peeeep** [comment]
Additionally to removing the play store geolock, publishing the apk directly (website / github / apkmirror / apkpure) would also allow users without access to the store to download the app.

**Comment by aurorasmiles** [comment]
Switching the country of your play store is only available once a year, which further increases this issue.

**Comment by stefan2904** [comment]
I think this also makes sense as part of the DP3T integration.

**Comment by uliluckas** [comment]
Play Store geo lock will be removed from the upcoming next version

**Comment by treysis** [comment]
Geolock is still active as of now.

**Comment by stefan2904** [comment]
> Geolock is still active as of now.

media reports says otherwise ... https://orf.at/stories/3171163/

**Comment by ghost** [comment]
Can't find it in the German app store with search terms "stoppcorona" and "stopp corona" as of now. Might be due to update delays in the app store, let's give it some time.

**Comment by treysis** [comment]
@stefan2904 actually not. The report says it's still in place until the change has propagated to all servers. However, when visiting manually using the direct link, the restriction should be lifted more or less immediately. However, this is not the case. Guess we need a few hours more.

**Comment by danez** [comment]
I also still see the geolock for germany. So I guess it takes a while for this changes to be applied.

**Comment by treysis** [comment]
Something is wrong. The geolock is still in place.

**Comment by uliluckas** [comment]
Please check again.

**Comment by treysis** [comment]
Working now!
