### ISSUE TITLE
timestampes from handshake are saved in not rounded format

### ISSUE THREAD

**Issue by TuxCoder** [austrianredcross/stopp-corona-android#21]
Currently saved timestamps from a handshake are saved secound exact,
This is different to what is shown and communicated publicly. Date and time should be rounded to the hours.

Examples from sqlite database:

table ```automatic_discovery```

|proximity|startTime|endTime|
|---------|----------|--------|
|4|1588031088|1588031575|

* proximity values observed between 0 and 5 - no clue what this would mean for the measured distance
* 1588031088 = 04/27/2020 @ 11:44pm (UTC) = 0x5EA76E70
* 1588031575 = 04/27/2020 @ 11:52pm (UTC) = 0x5EA77057

Even contacts with a duration less than 15min is saved in ```automatic_discovery```.
A posible solutin for this is to save the automatic discovery data only in memory.

table ```nearby_record```

|publicKey|timestamp|detectedAutomatically|
|---------|----------|--------|
|BLOB|1588017418|0|
|BLOB|1588031633|1|

**Comment by ManuelSchmitz** [comment]
I agree that the timestamp data should be rounded, preferably to the safe side (towards later, greater value).

However, more important is that the contact data is generally protected against extraction from the device. Storage in the process context of the operating system (or in some kind of TPM) would be  preferred. Raw contact data may never leave that protected area.

**Comment by devnsec** [comment]
@ManuelSchmitz this would be too much information for a tpm or secure zone because all the temporary contact information produced by p2pkit are saved to the database as well.

This p2pkit data in `automatic_discovery` includes contacts `publicKey` with `proximity` values and `startTime` + `endTime` for short periods (seconds to minutes) based on bluetooth scanner/discovery. 
From my tests this can be 10th of 'temporary' entries for a single contact.
After a while this information is correlated into a `nearby_record` as a single entry if the contact lasted in sum longer than 15min.

**Comment by uluckas** [comment]
I will look into saving rounded time stamps in `nearby_record`.
In `automatic_discovery` contact data needs to be stored with a more precise time stamps for about one hour for later aggregation.

**Comment by devnsec** [comment]
Would it be possible to store this 'raw' data in memory (list, hashmap whatever) instead of dumping everything into the database table `automatic_discovery`?

**Comment by uliluckas** [comment]
In the upcoming Google/Apple based implementation all scanning and key handling code will be replaced by the framework
