### ISSUE TITLE
Does it make sense to only notify contacts of the last 48 hours?

### ISSUE THREAD

**Issue by bauxi** [austrianredcross/stopp-corona-android#221]
... or am I missing something?

I try to paint a use case: When I show Covid symptoms, I need to call 1450, get a test and wait for the test results. This process takes in a best case 48 hours (currently probably longer) in which I hopefully already quarantined myself. So when I get the test result, I probably did not have much contacts within the last 48 hours and no one of my contacts before the test would be notified.

My solution for this problem would be to prolong the notification time frame? Something like: average testing time + 48 hours?

And yes, I know there is the possibility to alert when I am probably sick. But I guess most people won't do that if they have just a cough or something like that...

**Comment by ChristophDerndorfer** [comment]
This is indeed an issue and with the current delay between a test and getting the test result (>48 hours for almost everyone I personally know) it essentially makes the app useless in almost all cases.

However, I would propose a different solution: Allowing the reporter to optionally enter the day that their symptoms began before submitting the case. This also addresses the issue that most people aren't going to request (let alone actually get) a test on day 1 of their symptoms (especially in autumn with colds and the flu being everywhere).

Here's a (strictly hypothetical;-) example that shows how the current approach fails:

* Day 1: person A feels unwell
* Day 2: person A learns that someone she was previously in contact with tested positive, person A requests a test, and self-isolates
* Day 3: person A gets tested
* Day 5: person A gets the positive test result, person A reports the result via the app, nobody is informed since she was in self-quarantine already in the past 48 hours

So the current approach really only provides any value if the time between starting a self-quarantine and reporting a positive infection is less than 48 hours.

**Comment by bauxi** [comment]
So I found this info on Twitter:
![image](https://user-images.githubusercontent.com/12643214/97806971-85aad100-1c5e-11eb-91c5-528559962b8e.png)

As I understand it, if I send a yellow warning when my symptoms start, get the test positive test result and then turn it into a red warning, it would notify my contacts two days before I sent the yellow warning. But only IF I send the yellow warning immediately when the symptoms start. This works.

2 drawbacks here:
- I think, some people hesitate to send a warning the moment they get symptoms.
- If I'd only send a red warning, the use cases of the previous posts would still apply - no one would get notified.

I think, @ChristophDerndorfer makes a good point. Why not let the user report the day their symptoms started.

**Comment by ChristophDerndorfer** [comment]
@bauxi, thanks, that's useful information, but I agree with your concerns.

**Comment by jojoob** [comment]
> As I understand it, if I send a yellow warning when my symptoms start, get the test positive test result and then turn it into a red warning, it would notify my contacts two days before I sent the yellow warning. But only IF I send the yellow warning immediately when the symptoms start. This works.

I can confirm this by looking at the code. Only contacts of the [last two days](https://github.com/austrianredcross/stopp-corona-android/blob/d007643cff9db75bc75cfed53e967e4edb903fae/app/src/main/res/raw/configuration.json#L3) will be notified (technically speaking: only the TEKs of the last two days are uploaded) when reporting an infection (sending a yellow or red warning). [Except a red warning is send and a yellow warning was sent before the red warning will reach the same contacts](https://github.com/austrianredcross/stopp-corona-android/blob/d007643cff9db75bc75cfed53e967e4edb903fae/app/src/main/java/at/roteskreuz/stopcorona/model/repositories/ReportingRepository.kt#L194-L206) as the yellow one plus the contacts (hopefully not made) between sending the two warnings.

**Comment by ChristophDerndorfer** [comment]
Thanks for the confirmation @jojoob, much appreciated. I think at the very least this behaviour should be clearly explained in the app so that users are aware of it and actually send a yellow warning in case of a possible infection.

But I still believe that (maybe optionally?) allowing people to enter the date when their symptoms began would be a better solution.

**Comment by jojoob** [comment]
I'm also with you. I think the current behaviour reduces the usefulness of the app quite a lot.
Ask for when the symptoms began sounds like a good idea to me too.

**Comment by bauxi** [comment]
I'd close the issue because this seems fixed to me, but there is one last thing. There are two different workflows now: corona-verdacht melden where I am able to select the time when my symptoms started and ärztliche bestätigung melden where I cannot.
Why can't this just be einheitlich?
