### ISSUE TITLE
Dates from future possible and counting

### ISSUE THREAD

**Issue by TuxCoder** [austrianredcross/stopp-corona-android#29]
## Description

There is no data validation of dates and times in the app regarding a contact.
Old contacts are deleted but data from the future is kept.

The server cannot check for data errors in infection messages, because everything is encrypted.

![Screenshot_20200429-182210_Stopp_Corona](https://user-images.githubusercontent.com/2470864/80626896-646aed00-8a4f-11ea-89fe-2ce114f85623.png)

## Proposed solution:
add data validation for contact dates

**Comment by uluckas** [comment]
Thanks for your report @TuxCoder.

Contact time stamps are not validated because they are created by the app. What should we validate them against?

These dates are set by your local phone when you have your clock set forward.
If we delete the contacts once you set your clock back to normal, we would also delete valid contacts if you set your clock to the past. Not sure which issue is worse.

**Comment by devnsec** [comment]
@uluckas this is not an issue because of setting the clock of your phone to a wrong value.

When your app receive infection-messages they contain a timestamp which could NOT be validated by the server. So a malicious sender can send infection messages for the future.

Here is a link to a sample infection-info with some infection messages:
https://github.com/gstarnberger/covidsrv/issues/1

Here you see an packet to be encrypted:
```
[Cipher.getInstance()]: type: RSA/None/PKCS1Padding
[Cipher.getInstance()]:  cipherObj: javax.crypto.Cipher@573c5f8
[Cipher.init()]: mode: Encrypt mode, secretKey: com.android.org.conscrypt.OpenSSLRSAPublicKey , cipherObj: javax.crypto.Cipher@573c5f8
[Cipher.init()]: mode: Encrypt mode, secretKey: com.android.org.conscrypt.OpenSSLRSAPublicKey secureRandom:java.security.SecureRandom@22dc06a , cipherObj: javax.crypto.Cipher@573c5f8
[Cipher.doFinal2()]:   cipherObj: javax.crypto.Cipher@573c5f8
In buffer:

  Offset  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
00000000  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000020  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000030  00 00 00 00 00 00 00 00 00 00 00 00 00 72 00 00  .............r..
00000040  00 00 5E 90 6D D0 FE 7D 6D F9 6C 7D 48 81 96 45  ..^.m..}m.l}H..E
00000050  9D 1B EC 4B 38 D8                                ...K8.       
```
MessageType: `72 = 'r'`
Timestamp:	`5E 90 6D D0` = `1586523600` = `04/10/2020 @ 1:00pm (UTC)`
UUID: `FE7D6DF96C7D488196459D1BEC4B38D8` = `fe7d6df9-6c7d-4881-9645-9d1bec4b38d8`

This is the content of a infection message which can be later decrypted only be the correct phone.

A malicious sender could spoof these values and if there is no validation at the receiving side these values end up in the database.

**Comment by devnsec** [comment]
@uluckas I've rechecked the current code and according to the following file it seems to be fixed by now.

https://github.com/austrianredcross/stopp-corona-android/blob/master/app/src/main/java/at/roteskreuz/stopcorona/model/repositories/InfectionMessengerRepository.kt#L145

**Comment by TuxCoder** [comment]
If someone starts to implement a test framework,
this would be a great test case :)

**Comment by uluckas** [comment]
I see. Yes this has been fixed.
Thanks for reporting any way.

Feel free to contribute. Tests would be welcome.
