### ISSUE TITLE
Where is Issue #32

### ISSUE THREAD

**Issue by TuxCoder** [austrianredcross/stopp-corona-android#66]
As it's already a week since this issue gets remove and no reason appears for that,
I create this issue to find out what is going on.

Also the discussion would mess up other issues like it already has.

https://github.com/austrianredcross/meta/issues/8
https://github.com/austrianredcross/stopp-corona-android/issues/28

@tinkercnc
@devnsec

Please use this issue for discussion.

Link to old issue:
https://github.com/austrianredcross/stopp-corona-android/issues/32

I have a backup of it but I didn't want to republish it as there is normally a reason for this.
As I created it I tried to remove all personal information, also the issue was not a security issue, it was a privacy issue.

@mitsuhiko  Can you enlighten us?

**Comment by akuckartz** [comment]
> This issue has been moved to a repository you don't have access to.

**Comment by TuxCoder** [comment]
As I don't get any response, ticket is recreated https://github.com/austrianredcross/stopp-corona-android/issues/69 , if there is any issue, please tell me!

**Comment by tinkercnc** [comment]
Some sort of recursive issue... ;)

Thanks!

**Comment by bastianh** [comment]
We are currently in the process of removing p2pkit. It is already removed in the iOS development branch.

**Comment by tinkercnc** [comment]
It seems that some of the protagonist here use this strategy:
https://www.der-postillon.com/2017/05/life-hack-sprachnachrichten.html

**Comment by mitsuhiko** [comment]
@TuxCoder sorry I just saw this issue here now, i accidentally marked it as read and then missed out on the replies. As I said earlier I'm not the person who moved it.

As you have undoubtedly discovered p2pkit is not a great system for exchanging this information given how it operates. This is also why it's being phased out for a different approach. However unfortunately there is nothing that can be done on a temporary basis to improve this particular issue in the near term.

I would really like to reach out for a conversation about this particular issue and just some general questions. Do you mind me mailing at armin@ronacher.eu?

**Comment by mitsuhiko** [comment]
I'm going to close this issue as resolved. I am aware that this is probably not the answer you're looking for. I opened up the meta issue to discuss the future of the project in general: https://github.com/austrianredcross/meta/issues/8

If people want to get involved to improve the direction of the project and get involved, I would love to hear.
